USE [master]
GO
/****** Object:  Database [EmployeeDirectory]    Script Date: 3/11/2024 10:04:17 PM ******/
CREATE DATABASE [EmployeeDirectory]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EmployeeDirectory', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\EmployeeDirectory.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EmployeeDirectory_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\EmployeeDirectory_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [EmployeeDirectory] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EmployeeDirectory].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [EmployeeDirectory] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [EmployeeDirectory] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [EmployeeDirectory] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [EmployeeDirectory] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [EmployeeDirectory] SET ARITHABORT OFF 
GO
ALTER DATABASE [EmployeeDirectory] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [EmployeeDirectory] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [EmployeeDirectory] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [EmployeeDirectory] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [EmployeeDirectory] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [EmployeeDirectory] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [EmployeeDirectory] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [EmployeeDirectory] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [EmployeeDirectory] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [EmployeeDirectory] SET  DISABLE_BROKER 
GO
ALTER DATABASE [EmployeeDirectory] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [EmployeeDirectory] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [EmployeeDirectory] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [EmployeeDirectory] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [EmployeeDirectory] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [EmployeeDirectory] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [EmployeeDirectory] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [EmployeeDirectory] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [EmployeeDirectory] SET  MULTI_USER 
GO
ALTER DATABASE [EmployeeDirectory] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [EmployeeDirectory] SET DB_CHAINING OFF 
GO
ALTER DATABASE [EmployeeDirectory] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [EmployeeDirectory] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [EmployeeDirectory] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [EmployeeDirectory] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'EmployeeDirectory', N'ON'
GO
ALTER DATABASE [EmployeeDirectory] SET QUERY_STORE = ON
GO
ALTER DATABASE [EmployeeDirectory] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [EmployeeDirectory]
GO
/****** Object:  Table [dbo].[Employees]    Script Date: 3/11/2024 10:04:18 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employees](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](100) NULL,
	[MiddleName] [nvarchar](100) NULL,
	[LastName] [nvarchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [EmployeeDirectory] SET  READ_WRITE 
GO
